packages:
  - 'apps/*'

overrides:
  '@memeloop/libp2p': 0.2.2
  '@electron/rebuild': 4.2.0
  memeloop: 0.2.4
  node-abi: 4.33.0
  prebuild-install: latest
  node-addon-api: ^7.1.1

peerDependencyRules:
  allowedVersions:
    memeloop: '>=0.1.0 <0.3.0'

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - bufferutil
  - dprint
  - dugite
  - electron
  - electron-winstaller
  - esbuild
  - nsfw
  - registry-js
  - unrs-resolver
  - utf-8-validate
