export default {
  AgentBrowser: Symbol.for('AgentBrowser'),
  AgentDefinition: Symbol.for('AgentDefinition'),
  AgentInstance: Symbol.for('AgentInstance'),
  Analytics: Symbol.for('Analytics'),
  Context: Symbol.for('Context'),
  Database: Symbol.for('Database'),
  DeepLink: Symbol.for('DeepLinkService'),
  DeviceNetwork: Symbol.for('DeviceNetworkService'),
  ExternalAPI: Symbol.for('ExternalAPI'),
  ProviderRegistry: Symbol.for('ProviderRegistry'),
  NativeService: Symbol.for('NativeService'),
  NotificationService: Symbol.for('NotificationService'),
  Preference: Symbol.for('Preference'),
  RemoteSetup: Symbol.for('RemoteSetup'),
  SystemPreference: Symbol.for('SystemPreference'),
  ThemeService: Symbol.for('ThemeService'),
  ToolPermissions: Symbol.for('ToolPermissions'),
  Updater: Symbol.for('Updater'),
  Window: Symbol.for('Window'),
};
