export default {
  AgentBrowser: Symbol.for('AgentBrowser'),
  AgentDefinition: Symbol.for('AgentDefinition'),
  AgentInstance: Symbol.for('AgentInstance'),
  Analytics: Symbol.for('Analytics'),
  Authentication: Symbol.for('Authentication'),
  Context: Symbol.for('Context'),
  Database: Symbol.for('Database'),
  DeepLink: Symbol.for('DeepLinkService'),
  DeviceNetwork: Symbol.for('DeviceNetworkService'),
  ExternalAPI: Symbol.for('ExternalAPI'),
  ProviderRegistry: Symbol.for('ProviderRegistry'),
  Git: Symbol.for('Git'),
  GitServer: Symbol.for('GitServer'),
  HtmlWiki: Symbol.for('HtmlWiki'),
  MemeloopNode: Symbol.for('MemeloopNode'),
  MenuService: Symbol.for('MenuService'),
  NativeService: Symbol.for('NativeService'),
  NotificationService: Symbol.for('NotificationService'),
  Preference: Symbol.for('Preference'),
  RemoteSetup: Symbol.for('RemoteSetup'),
  Sync: Symbol.for('Sync'),
  SystemPreference: Symbol.for('SystemPreference'),
  ThemeService: Symbol.for('ThemeService'),
  ToolPermissions: Symbol.for('ToolPermissions'),
  Updater: Symbol.for('Updater'),
  View: Symbol.for('View'),
  Window: Symbol.for('Window'),
  // Stubbed wiki/workspace services (implementation removed, kept for compilation)
  Wiki: Symbol.for('Wiki'),
  Workspace: Symbol.for('Workspace'),
  WorkspaceView: Symbol.for('WorkspaceView'),
  WikiEmbedding: Symbol.for('WikiEmbedding'),
  WikiGitWorkspace: Symbol.for('WikiGitWorkspace'),
};
